name: interact2
description: A collection of customizable interactive command-line components.
version: 3.0.0
repository: https://github.com/appfluent/interact2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console: ^4.1.2
  meta: ^1.16.0
  tint: ^2.0.1

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.2
